---
collections:
# With just the collection name
#- community.general
#- awx.awx
#- oracle.oci
#- infoblox.nios_modules
#- myfirst.test_collection
#- vyos.vyos
#- community.vmware
- name: 'https://github.com/jbird2021/ansible-tower-samples/blob/master/freeipa-ansible_freeipa-1.6.2.tar.gz'
