# Add new.foo.com as an A record with 3 IPs and wait until the changes have been replicated
---
- name: Add a new AWS route53 DNS A record
  hosts: all
#  gather_facts: no
#  connection: local

  tasks:
    - name: Basic env usage
      debug:
        msg: "'{{ lookup('env', 'AWX_HOST') }}' is the AWX_HOST environment variable."

    - name: Print some variables
      vars:
        msg: |
            Ansible Distribution: {{ ansible_distribution }}
            Ansible Dist version: {{ ansible_distribution_version }}
#            ACM Deployment {{cluster_deployment}}
            ACM Base Domain {{cluster_deployment['baseDomain']}}
            ACM Cluster name {{cluster_deployment['clusterName']}}
            API record api.{{cluster_deployment['clusterName']}}.{{cluster_deployment['baseDomain']}}
            Ingress record  *.apps.{{cluster_deployment['clusterName']}}.{{cluster_deployment['baseDomain']}}
      debug:
        msg: "{{ msg.split('\n') }}"



#  - name:
#    community.aws.route53:
#      command: create
#      zone: foo.com
#      record: new.foo.com
#      type: A
#      ttl: 7200
#      value: 1.1.1.1
#      wait: yes
