---
- name: whatever
  hosts: "{{ hosts_to_run | default ('all') }}"
  gather_facts: false
  tasks:
    - name: Configure inside interface
      cisco.asa.asa_config:
        lines:
        - description inside interface
        - no shutdown
        - nameif inside
        - security-level 100
        - ip address 10.10.51.70 255.255.255.0
        parents: [interface GigabitEthernet0/2]
