---
- name: "Playbook to test dictionary variable in Tower."
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    app_config: "{{ app_config }}"
    dedicated_app_config:
      WEBSITES_PORT: "9080"
      WEBSITE_VNET_ROUTE_ALL: "1"
  tasks:  
    - name: "Combine dictionaries."
      ansible.builtin.debug:
        msg: "{{ app_config | combine(dedicated_app_config) }}"
