---
- name: "Playbook to test dictionary variable in Tower."
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    app_config:
    app_config_dict: "{{ app_config:splitlines()|map('from_yaml')|list }}"
    dedicated_app_config:
      WEBSITES_PORT: "9080"
      WEBSITE_VNET_ROUTE_ALL: "1"

  tasks:
    - name: "Display value."
      ansible.builtin.debug:
        msg: "{{ app_config }}"

    - name: "Display type."
      ansible.builtin.debug:
        msg: "{{ app_config | type_debug }}"

    - name: "Display value from json."
      ansible.builtin.debug:
        msg: "{{ app_config | from_json }}"
      when: "app_config is string"

    - name: "Convert input to appropriate type."
      ansible.builtin.set_fact:
        app_config: "{{ app_config | from_json }}"
      when: "app_config is string"

    - name: "Display value."
      ansible.builtin.debug:
        msg: "{{ app_config }}"

    - name: "Display type."
      ansible.builtin.debug:
        msg: "{{ app_config | type_debug }}"


    - name: "Display value2."
      ansible.builtin.debug:
        msg: "{{ dedicated_app_config }}"

    - name: "Display type2."
      ansible.builtin.debug:
        msg: "{{ dedicated_app_config | type_debug }}"

    - name: "Display value from json2."
      ansible.builtin.debug:
        msg: "{{ dedicated_app_config | from_json }}"
      when: "dedicated_app_config is string"

    - name: "Convert input to appropriate type2."
      ansible.builtin.set_fact:
        app_config: "{{ dedicated_app_config | from_json }}"
      when: "dedicated_app_config is string"

    - name: "Display value2."
      ansible.builtin.debug:
        msg: "{{ dedicated_app_config }}"

    - name: "Display type2."
      ansible.builtin.debug:
        msg: "{{ dedicated_app_config | type_debug }}"
        
        
        
    - name: "Display value3"
      ansible.builtin.debug:
        msg: "{{ app_config_dict }}"

    - name: "Display type3."
      ansible.builtin.debug:
        msg: "{{ app_config_dict | type_debug }}"

    - name: "Display value from json3."
      ansible.builtin.debug:
        msg: "{{ app_config_dict | from_json }}"
      when: "app_config_dict is string"

    - name: "Convert input to appropriate type3."
      ansible.builtin.set_fact:
        app_config: "{{ app_config_dict | from_json }}"
      when: "app_config_dict is string"

    - name: "Display value3"
      ansible.builtin.debug:
        msg: "{{ app_config_dict }}"

    - name: "Display type3"
      ansible.builtin.debug:
        msg: "{{ app_config_dict | type_debug }}"       
        
        
        
        
        
    - name: "Combine dictionaries."
      ansible.builtin.debug:
        msg: "{{ app_config_dict | combine(dedicated_app_config) }}"
