---
- name: dump all
  hosts: all

  tasks:
    - name: Print Ansible version information
      vars:
        msg: |
            Ansible Distribution: {{ ansible_distribution }}
            Ansible Dist version: {{ ansible_distribution_version }}
      debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info

  - debug: msg="Cluster {{action}}. Current cluster list {{target_clusters}}"

  - debug: msg="Ansible tower {{AWX_HOST}}. Base Domain {{cluster_deployment.baseDomain}} "
    - name: Print more debug information
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

      debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info
