- name: Hello World Sample
  hosts: localhost
  vars: 
    - mydict: {
               'Name': 'MyTestName', 
               'Password': 'MyTestPassword'
               }
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Set dns account
      vars:
        vars:
          vm_location: "test"
      set_fact:
        dns_account: "{{ mydict[Name] }}"
      when:
        - vm_location is defined
