- name: Hello World Sample
  hosts: all
  # gather_facts: false
  connection: ssh
  tasks:
    - name: Hello Message
      debug:
      
        msg: "Hello World!"
    - name: Create private endpoint
      azure_rm_privateendpoint:
        name: "azr_pve_name"
        subscription_id: "azr_subid"
        resource_group: "azr_rg_name"
        state: present
        auth_source: auto
        private_link_service_connections:
          - name: "azr_pve_name"
            private_link_service_id: /subscriptions/azr_subid/resourceGroups/azr_rg_name/providers/Microsoft.KeyVault/vaults/azr_kv_name
            group_ids: 
              - "azr_pve_sub_resource"
        subnet:
          id: /subscriptions/azr_subid/resourceGroups/azr_rg_name/providers/Microsoft.Network/virtualNetworks/azr_vnet_name/subnets/azr_snet_sec
        tags:
            Description: "Private Endpoint: For Resource azr_kv_name"
            Subscription: "subscode"
            AppCode: "appcode"
            AppOwner: "appowner"
            Environment: "envcode"
            Location: "locationus"
            Instance: "pve_kv_instance"
            ResourceType: pve
