- name: Hello World Sample
  hosts: localhost
  gather_facts: True
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: Copy a folder
      copy:
        src: /tmp/test/
        dest: /tmp/test2/
        remote_src: yes

