- name: Hello World Sample
  hosts: all
  gather_facts: False
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
      vars:
        ansible_command_timeout: 2
    
    - name: Say Hello
      debug:
        msg: "Hello World!"
        
    - name: Induce an exception to see what happens
      ansible.builtin.ping:
        data: crash
