- name: Hello World Sample
  hosts: localhost
  vars: 
    - mydict: {
               'Name': 'MyTestName', 
               'Password': 'MyTestPassword'
               }
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Set dns account
      set_fact:
        dns_account: "{{ mydict}}"
