- name: Hello World Sample
  hosts: all
  # gather_facts: false
  connection: ssh
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Ensure IIS Web server is installed
      ansible.windows.win_feature:
        name: 'Web-Server'
        state: present
      register: install_features
