- name: Hello World Sample
  hosts: all
  gather_facts: True
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
      vars:
        ansible_command_timeout: 2
    
    - name: Say Hello
      debug:
        msg: "Hello World!"
