- name: Hello World Sample
  hosts: localhost
  gather_facts: True
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: Ping
      debug:
        msg: "{{ password }}"
        no_log: True

