- name: Hello World Sample
  hosts: all
  # gather_facts: false
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Refresh DNSMASQ Service
      systemd:
        state: restarted
        name: dnsmasq
      become: yes
      become_user: ansibleadm
