- name: Hello World Sample
  hosts: localhost
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ anisble_password }}'
  tasks:
    - name: Hello Message
      debug:
#        msg: "Hello World!"
        var: machine

