# - name: Hello World Sample
#  hosts: localhost
#  vars:
#    machine_test:
#      username: '{{ ansible_user }}'
#      password: '{{ anisble_password }}'
#  tasks:
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"
- name: My Test Playbook
  hosts: localhost
  no_log: True 
  vars: 
    - mydict: {
               'Name': 'MyTestName', 
               'Password': 'MyTestPassword'
               }
  tasks:
    - name: Set dns account
      set_fact:
        dns_account: "{{ mydict}}"
      no_log: True 
