- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World after forking to my git hub!"
      
    - name: copy module
      copy:
        content: "create file by me"
        dest: /root/my_change
        
