- name: Hello World Sample
  hosts: all
  # gather_facts: false
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Make temp directory for Python virtualenv
      tempfile:
        state: directory
        prefix: zabbix_monitoring.
      register: tempvenv
      delegate_to: localhost
      become: no

    - name: Install the zabbix-api Python module
      pip:
        name: zabbix-api
        virtualenv: "{{ tempvenv.path }}"
        virtualenv_site_packages: yes
      delegate_to: localhost
      become: no
