- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Set dns account
      set_fact:
        dns_account: "{{ vars[vm_location + '_dns'] }}"
      when:
        - vm_location is defined
