- name: Hello World Sample
  hosts: localhost
  gather_facts: True
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: run the new module
      lockbox:
        name: 'hello'
      #new: true
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
