- name: My Test
  hosts: localhost
  gather_facts: no
#  vars:
#    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: Gather variables
      include_vars: /etc/ansible/vault.yml
