- name: Ansible Automation Platform Backup
  hosts: localhost
  gather_facts: no
  
  tasks:
     - name: Nightly Automation Platform Backups
       #become: true
       command: /tmp/stupid/ansible-tower-setup-bundle-3.8.4-1/.setup.sh -e /"backup_dest=/tmp/stupid/ansible-tower-setup-bundle-3.8.4-1//" -b
