- name: My Test
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx
  settings:
    name: "AWX_ISOLATION_SHOW_PATHS"
    value: "'/etc/ansible/'"
  register: testing_settings
  tasks:
    - name: Say Hello
      include_vars: /etc/ansible/vault.yml
