- name: backup vyos
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: configurable backup path
    vyos.vyos.vyos_config:
      backup: yes
      backup_options:
        dir_path: /home/ansible/vyos-bakup/
