- name: My Test
  hosts: localhost
  gather_facts: no
#- name: Set the value of AWX_ISOLATION_BASE_PATH
#  settings:
#    name: AWX_ISOLATION_BASE_PATH
#    value: "'/etc/ansible'"
#  register: testing_settings
- name: Set the value of AWX_ISOLATION_SHOW_PATHS
  settings:
    name: "AWX_ISOLATION_SHOW_PATHS"
    value: "'/etc/ansible/','/tmp'"
  register: testing_settings
  tasks:
    - name: Say Hello
      include_vars: /etc/ansible/vault.yml
