- name: Hello World Sample
  hosts: localhost
  gather_facts: True 
  tasks:   
    - name: Read users from CSV file and return a list
      read_csv:
        path: non-prod-ssl.csv
      register: results
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: 'Host {{ results.list.1.HOSTNAME }} has UID {{ results.list.1.PORT }}'
