- name: Hello World Sample
  hosts: localhost
  gather_facts: True 
  tasks:   
    - name: Read users from CSV file and return a list
      read_csv:
        path: /opt/non-prod-ssl.csv
      register: results
      delegate_to: localhost

  #  - ansible.builtin.debug:
  #      msg: 'Host {{ results.list.1.HOSTNAME }} has UID {{ results.list.1.PORT }}'
        
        
    - name: Display CSV file only host and port and create 
      get_certificate:
        host: "{{ item.HOSTNAME }}"
        port: "{{ item.PORT }}"
      run_once: true
      register: cert
      delegate_to: localhost
      ignore_errors: yes
      loop: "{{ results.list }}"

    - name: get cert information
      debug:
        msg:  "Certificate subject {{ item.subject.CN }}, extensions values {{''.join(item.extensions[1].asn1_data)  }} , validity {{ (item.not_before | to_datetime('%Y%m%d%H%M%SZ')) }}"
      when: item.failed != True
      register: cert_details
      ignore_errors: yes
      loop: "{{ cert.results }}"

    - name: display cert_details
      debug: var=cert_details

    - name: write cert_details to csv file
      template:
        src: /opt/generate_csv.j2
        dest: /tmp/certs_details.csv
