- name: Hello World Sample
  hosts: localhost
  gather_facts: True 
  tasks:   
    - name: read host and port from a csv file
      community.general.read_csv:
        path: /tmp/non-prod-ssl.csv
        # key: HOSTNAME
        # delimiter: ','
      register: results
      delegate_to: localhost


 #   - name: Display CSV file only host and port and create 
 #     community.crypto.get_certificate:
 #       host: "{{ item.HOSTNAME }}"
 #       port: "{{ item.PORT }}"
 #     run_once: true
 #     register: cert
 #     delegate_to: localhost
 #     ignore_errors: yes
 #     loop: "{{ results.list }}"

 #   - name: get cert information
 #     debug:
 #       msg:  "Certificate subject {{ item.subject.CN }}, extensions values {{''.join(item.extensions[1].asn1_data)  }} , validity {{ (item.not_before | to_datetime('%Y%m%d%H%M%SZ')) }}"
 #     when: item.failed != True
 #     register: cert_details
 #     ignore_errors: yes
 #     loop: "{{ cert.results }}"

 #   - name: display cert_details
 #     debug: var=cert_details

 #   - name: write cert_details to csv file
 #     template:
 #       src: generate_csv.j2
 #       dest: certs_details.csv
