- name: Hello World Sample
  hosts: localhost
  gather_facts: False
  vars:
    vcenter_hostname: "localhost"
    vcenter_username: "vcenter_username"
    vcenter_password: "vcenter_password"
    dc: "dc"
    target_host: "target_host"
  tasks:   
    - name: Say Hello
      debug:
        msg: "Hello World!"
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
      delegate_to: localhost
      register: vminfo
    - debug:
        var: vminfo.virtual_machines
