---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: all
  vars:
    http_port: 8080
    https_port: 8443
    admin_username: admin
    admin_password: adminsecret
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - tomcat
